-- Saved recipients ("agenda"): accounts of other clients a client transfers to, with an alias.
-- holder_display is a masked name ("Lucía P.") captured when the contact is added.

CREATE TABLE contact (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id      BIGINT       NOT NULL,
    alias          VARCHAR(40)  NOT NULL,
    account_number VARCHAR(20)  NOT NULL,
    holder_display VARCHAR(60)  NOT NULL,
    created_at     TIMESTAMP    NOT NULL,
    CONSTRAINT fk_contact_client FOREIGN KEY (client_id) REFERENCES client (id),
    CONSTRAINT uk_contact_account UNIQUE (client_id, account_number)
);
