-- Fixed-term deposits ("plazo fijo"): money locked for a term at a fixed annual rate (TNA), paid back
-- with simple interest on the maturity date.

CREATE TABLE fixed_term_plan (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    term_days   INTEGER       NOT NULL,
    annual_rate NUMERIC(5, 4) NOT NULL,
    CONSTRAINT uk_fixed_term_plan_days UNIQUE (term_days),
    CONSTRAINT ck_fixed_term_plan_rate CHECK (annual_rate > 0 AND annual_rate < 10)
);

CREATE TABLE fixed_term (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id     BIGINT         NOT NULL,
    account_id    BIGINT         NOT NULL,
    principal     NUMERIC(19, 2) NOT NULL,
    annual_rate   NUMERIC(5, 4)  NOT NULL,
    term_days     INTEGER        NOT NULL,
    interest      NUMERIC(19, 2) NOT NULL,
    start_date    DATE           NOT NULL,
    maturity_date DATE           NOT NULL,
    auto_renew    BOOLEAN        NOT NULL,
    status        VARCHAR(10)    NOT NULL,
    paid_at       TIMESTAMP,
    renewed_from  BIGINT,
    CONSTRAINT fk_fixed_term_client FOREIGN KEY (client_id) REFERENCES client (id),
    CONSTRAINT fk_fixed_term_account FOREIGN KEY (account_id) REFERENCES account (id),
    -- renewed_from: id of the fixed term this one reinvests (informative, no FK: rows are never deleted).
    CONSTRAINT ck_fixed_term_status CHECK (status IN ('ACTIVE', 'PAID')),
    CONSTRAINT ck_fixed_term_amounts CHECK (principal > 0 AND interest >= 0)
);

CREATE INDEX ix_fixed_term_client ON fixed_term (client_id);
CREATE INDEX ix_fixed_term_due ON fixed_term (status, maturity_date);

INSERT INTO fixed_term_plan (term_days, annual_rate) VALUES
    (30, 0.3500),
    (60, 0.3600),
    (90, 0.3700),
    (180, 0.3800),
    (365, 0.4000);
