-- In-app notifications (the bell) and each client's alert preferences.
-- Portable between H2 (dev/test) and PostgreSQL (prod).

CREATE TABLE notification (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id  BIGINT       NOT NULL,
    type       VARCHAR(30)  NOT NULL,
    title      VARCHAR(120) NOT NULL,
    message    VARCHAR(500) NOT NULL,
    link       VARCHAR(200),
    created_at TIMESTAMP    NOT NULL,
    read_at    TIMESTAMP,
    CONSTRAINT fk_notification_client FOREIGN KEY (client_id) REFERENCES client (id)
);

CREATE INDEX ix_notification_client_created ON notification (client_id, created_at);

-- Thresholds in ARS; NULL = that alert is off. Sign-in alerts and e-mail copies start on.
ALTER TABLE client ADD COLUMN alert_low_balance NUMERIC(19, 2);
ALTER TABLE client ADD COLUMN alert_large_movement NUMERIC(19, 2);
ALTER TABLE client ADD COLUMN alert_login BOOLEAN DEFAULT TRUE NOT NULL;
ALTER TABLE client ADD COLUMN alert_email BOOLEAN DEFAULT TRUE NOT NULL;
