-- Scheduled transfers: once on a date, or weekly/monthly from a start date, run by a daily job.
-- next_index counts occurrences from start_date (skipped ones included), runs counts executions.
-- Portable between H2 (dev/test) and PostgreSQL (prod).

CREATE TABLE scheduled_transfer (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id             BIGINT         NOT NULL,
    source_account_id     BIGINT         NOT NULL,
    target_account_number VARCHAR(20)    NOT NULL,
    target_holder         VARCHAR(60)    NOT NULL,
    amount                NUMERIC(19, 2) NOT NULL,
    description           VARCHAR(100),
    frequency             VARCHAR(10)    NOT NULL,
    start_date            DATE           NOT NULL,
    next_index            INTEGER        NOT NULL,
    next_run              DATE,
    runs                  INTEGER        NOT NULL,
    max_runs              INTEGER,
    status                VARCHAR(10)    NOT NULL,
    last_run_at           TIMESTAMP,
    last_outcome          VARCHAR(10),
    last_error            VARCHAR(120),
    created_at            TIMESTAMP      NOT NULL,
    CONSTRAINT fk_scheduled_client FOREIGN KEY (client_id) REFERENCES client (id),
    CONSTRAINT fk_scheduled_source FOREIGN KEY (source_account_id) REFERENCES account (id),
    CONSTRAINT ck_scheduled_amount CHECK (amount > 0),
    CONSTRAINT ck_scheduled_frequency CHECK (frequency IN ('ONCE', 'WEEKLY', 'MONTHLY')),
    CONSTRAINT ck_scheduled_status CHECK (status IN ('ACTIVE', 'PAUSED', 'FINISHED', 'CANCELLED'))
);

CREATE INDEX ix_scheduled_due ON scheduled_transfer (status, next_run);
CREATE INDEX ix_scheduled_client ON scheduled_transfer (client_id);
