-- Initial schema. Portable between H2 (dev/test) and PostgreSQL (prod).

CREATE TABLE client (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(50)  NOT NULL,
    last_name  VARCHAR(50)  NOT NULL,
    email      VARCHAR(255) NOT NULL,
    password   VARCHAR(255) NOT NULL,
    role       VARCHAR(20)  NOT NULL,
    CONSTRAINT uk_client_email UNIQUE (email),
    CONSTRAINT ck_client_role CHECK (role IN ('CLIENT', 'ADMIN'))
);

CREATE TABLE account (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number        VARCHAR(20)    NOT NULL,
    creation_date TIMESTAMP      NOT NULL,
    balance       NUMERIC(19, 2) NOT NULL,
    client_id     BIGINT         NOT NULL,
    CONSTRAINT uk_account_number UNIQUE (number),
    CONSTRAINT fk_account_client FOREIGN KEY (client_id) REFERENCES client (id)
);

CREATE INDEX ix_account_client ON account (client_id);

CREATE TABLE refresh_token (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash VARCHAR(64)              NOT NULL,
    client_id  BIGINT                   NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked    BOOLEAN                  NOT NULL,
    CONSTRAINT uk_refresh_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_token_client FOREIGN KEY (client_id) REFERENCES client (id)
);

CREATE INDEX ix_refresh_token_client ON refresh_token (client_id);
