-- Accounts can be closed (soft delete) and record their movements.

ALTER TABLE account ADD COLUMN active BOOLEAN DEFAULT TRUE NOT NULL;

CREATE TABLE account_transaction (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type          VARCHAR(10)    NOT NULL,
    amount        NUMERIC(19, 2) NOT NULL,
    description   VARCHAR(255)   NOT NULL,
    occurred_at   TIMESTAMP      NOT NULL,
    balance_after NUMERIC(19, 2) NOT NULL,
    account_id    BIGINT         NOT NULL,
    CONSTRAINT fk_transaction_account FOREIGN KEY (account_id) REFERENCES account (id),
    CONSTRAINT ck_transaction_type CHECK (type IN ('CREDIT', 'DEBIT')),
    CONSTRAINT ck_transaction_amount CHECK (amount > 0)
);

CREATE INDEX ix_transaction_account_date ON account_transaction (account_id, occurred_at);
