-- Payment cards. Only the last 4 digits and a SHA-256 hash of the card number are stored; never the CVV.

CREATE TABLE card (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cardholder  VARCHAR(101) NOT NULL,
    type        VARCHAR(10)  NOT NULL,
    color       VARCHAR(10)  NOT NULL,
    last4       VARCHAR(4)   NOT NULL,
    number_hash VARCHAR(64)  NOT NULL,
    from_date   DATE         NOT NULL,
    thru_date   DATE         NOT NULL,
    active      BOOLEAN      NOT NULL,
    client_id   BIGINT       NOT NULL,
    CONSTRAINT uk_card_number_hash UNIQUE (number_hash),
    CONSTRAINT fk_card_client FOREIGN KEY (client_id) REFERENCES client (id),
    CONSTRAINT ck_card_type CHECK (type IN ('CREDIT', 'DEBIT')),
    CONSTRAINT ck_card_color CHECK (color IN ('GOLD', 'SILVER', 'TITANIUM'))
);

CREATE INDEX ix_card_client ON card (client_id);
