-- Loan catalog (reference data) and the loans granted to clients.

CREATE TABLE loan (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          VARCHAR(20)    NOT NULL,
    name          VARCHAR(50)    NOT NULL,
    max_amount    NUMERIC(19, 2) NOT NULL,
    interest_rate NUMERIC(5, 4)  NOT NULL,
    CONSTRAINT uk_loan_code UNIQUE (code)
);

CREATE TABLE loan_payment (
    loan_id  BIGINT  NOT NULL,
    payments INTEGER NOT NULL,
    CONSTRAINT fk_loan_payment_loan FOREIGN KEY (loan_id) REFERENCES loan (id)
);

CREATE TABLE client_loan (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id     BIGINT         NOT NULL,
    loan_id       BIGINT         NOT NULL,
    amount        NUMERIC(19, 2) NOT NULL,
    total_due     NUMERIC(19, 2) NOT NULL,
    payments      INTEGER        NOT NULL,
    payments_made INTEGER        NOT NULL,
    outstanding   NUMERIC(19, 2) NOT NULL,
    created_at    TIMESTAMP      NOT NULL,
    CONSTRAINT fk_client_loan_client FOREIGN KEY (client_id) REFERENCES client (id),
    CONSTRAINT fk_client_loan_loan FOREIGN KEY (loan_id) REFERENCES loan (id),
    CONSTRAINT ck_client_loan_payments CHECK (payments_made >= 0 AND payments_made <= payments),
    CONSTRAINT ck_client_loan_outstanding CHECK (outstanding >= 0)
);

CREATE INDEX ix_client_loan_client ON client_loan (client_id);

-- Same products as the original app: 20% interest.
INSERT INTO loan (id, code, name, max_amount, interest_rate) VALUES
    (1, 'MORTGAGE',   'Hipotecario', 500000.00, 0.2000),
    (2, 'PERSONAL',   'Personal',    100000.00, 0.2000),
    (3, 'AUTOMOTIVE', 'Automotor',   300000.00, 0.2000);

INSERT INTO loan_payment (loan_id, payments) VALUES
    (1, 12), (1, 24), (1, 36), (1, 48), (1, 60),
    (2, 6), (2, 12), (2, 24),
    (3, 6), (3, 12), (3, 24), (3, 36);

-- Explicit ids above: move the identity past them (valid in H2 and PostgreSQL).
ALTER TABLE loan ALTER COLUMN id RESTART WITH 4;
