-- Single-use password reset tokens. Only the SHA-256 hash of the token is stored.

CREATE TABLE password_reset_token (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash VARCHAR(64)              NOT NULL,
    client_id  BIGINT                   NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    used_at    TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_password_reset_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_password_reset_token_client FOREIGN KEY (client_id) REFERENCES client (id)
);

CREATE INDEX ix_password_reset_token_client ON password_reset_token (client_id);
