-- Append-only audit trail. The application never updates or deletes rows.

CREATE TABLE audit_event (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    actor       VARCHAR(255),
    actor_role  VARCHAR(20),
    action      VARCHAR(50)  NOT NULL,
    target      VARCHAR(120),
    outcome     VARCHAR(10)  NOT NULL,
    ip          VARCHAR(45),
    details     VARCHAR(500),
    CONSTRAINT ck_audit_outcome CHECK (outcome IN ('SUCCESS', 'FAILURE'))
);

CREATE INDEX ix_audit_occurred_at ON audit_event (occurred_at);
CREATE INDEX ix_audit_actor ON audit_event (actor);
CREATE INDEX ix_audit_action ON audit_event (action);
