-- Stored results of non-idempotent requests (transfers, loans...) keyed by the client-supplied
-- Idempotency-Key, so a retried request returns the original result instead of running twice.

CREATE TABLE idempotency_record (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner           VARCHAR(255)             NOT NULL,
    idem_key        VARCHAR(100)             NOT NULL,
    operation       VARCHAR(50)              NOT NULL,
    request_hash    VARCHAR(64)              NOT NULL,
    response_status INTEGER                  NOT NULL,
    response_body   VARCHAR(4000)            NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_idempotency_owner_key UNIQUE (owner, idem_key)
);

CREATE INDEX ix_idempotency_created_at ON idempotency_record (created_at);
