package com.mindhub.homebanking.domain;

/** Security- and money-relevant events kept in the audit trail. */
public enum AuditAction {
    LOGIN,
    LOGIN_LOCKED,
    LOGOUT,
    REGISTER,
    PASSWORD_CHANGED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET,
    TWO_FACTOR_ENABLED,
    TWO_FACTOR_DISABLED,
    TWO_FACTOR_RESET,
    CLIENT_CREATED,
    CLIENT_BLOCKED,
    CLIENT_UNBLOCKED,
    ACCOUNT_OPENED,
    ACCOUNT_CLOSED,
    ACCOUNT_ALIAS_CHANGED,
    TRANSFER,
    CONTACT_ADDED,
    CONTACT_REMOVED,
    CARD_ISSUED,
    CARD_DEACTIVATED,
    LOAN_APPROVED,
    LOAN_INSTALLMENT_PAID,
    FIXED_TERM_CREATED,
    FIXED_TERM_PAID,
    FIXED_TERM_RENEWED
}
